### ISSUE TITLE
Plugin is not updating from within Sketch Preferences

### ISSUE THREAD

**Issue by robdell** [EricKramp/sketch-table-builder#1]
The latest update is not loading when the "Update" icon is clicked in Sketch Prefences>Plugins

**Comment by dlewand691** [comment]
Seeing the same, says "3.0.0 Available"
![CleanShot 2020-12-10 at 09 22 41](https://user-images.githubusercontent.com/1159913/101784299-568f4700-3ac9-11eb-8e00-e8b6a914fd5a.jpg)

**Comment by wdm-123** [comment]
I am finding the same issue.  Sketch keeps indicating that a Plugin update is available, yet the Sketch-table-builder is the only plugin that needs to be updated.  Pressing the "Update" button does nothing.

![PluginUpdateMsg](https://user-images.githubusercontent.com/60984718/101814434-29a05b80-3aec-11eb-9cfa-105fc71d15e5.jpg)

**Comment by vaporboy** [comment]
I also noticed that when downloading the released installer for version 0.1.2 that the installer tries to install version 0.1 which is already installed.

**Comment by xingzhuo** [comment]
Hi,EricKramp！ Thank you for your work, this is a great tool, but it would be perfect if you can define a fixed width for the entire table!

**Comment by Landschaft** [comment]
Hi @EricKramp – thank you very much for this plugin that has saved me a ton of time!

As others have mentioned before, the version metadata of the plugin is incorrect, resulting in some confusion. 

Although I have no practical experience in development of Sketch plugins, it seems to me that the problem are the last three entries from the [.appcast.xml](https://raw.githubusercontent.com/EricKramp/sketch-table-builder/master/.appcast.xml) file which point to non-existing releases of the plugin.

Maybe the problem could be solved by just removing these entries from the file?

**Comment by EricKramp** [comment]
Hi All, so sorry about that! I'm not sure how those bad version numbers got added to the appcast, but it should be resolved now.

The new release, which only fixes this update bug is `0.1.4` should be hitting your notifications any minute.

@Landschaft thanks so much for the @ mention, for some reason I haven't been notified of any of these other conversations.

@vaporboy, @dlewand691, @robdell, sorry to leave you hanging with that annoying behavior for so long!

@xingzhuo, thanks for the suggestion. I'm going to move your request to a new issue.
