### ISSUE TITLE
All table cells are filled with the same content

### ISSUE THREAD

**Issue by Landschaft** [EricKramp/sketch-table-builder#4]
I'm using Sketch 91 and sketch-table-builder 0.1.4.

When I use the plugin with the following CSV:

    Status,Type
    New,request

It will result in a 2 x 2 table having all four cells set to "Status" (the cells' names are set correctly):

![Screenshot 2022-08-11 at 11 56 50](https://user-images.githubusercontent.com/10559398/184109320-942f769a-0b24-46a0-92d9-d1b9ecef09cd.png)

From the console:

    finished parse! : Status,Type,New,request
    table-builder.build-identifier
    row: 0
    table-builder.build-identifier
    Status
    table-builder.build-identifier
    Type
    table-builder.build-identifier
    row: 1
    table-builder.build-identifier
    New	table-builder.build-identifier
    request

**Comment by Landschaft** [comment]
This used to work before. BTW: I use table cells from the [Carbon DS](https://carbondesignsystem.com/designing/kits/sketch/)

@EricKramp any ideas how this could have degenerate?

**Comment by Landschaft** [comment]
It seems to me that this is a bug in Sketch 91

**Comment by EricKramp** [comment]
Thanks for the heads up @Landschaft, I'm seeing the same bug you are in Sketch 91 even with my demo file. There aren't any errors being thrown, so I'll need to look into it a bit to figure out what changed.

**Comment by Landschaft** [comment]
I’ve filed a bug report with the Sketch support team. Unfortunately,
there’s no ticket that I could share with you. They told me that they are
looking into it. I’ll keep this thread updated.

**Comment by bomberstudios** [comment]
Hi there: I’m currently investigating this issue and will report back when we find anything. Thanks for your patience!

**Comment by bomberstudios** [comment]
I can confirm this is an issue on our side (an unintended consequence of a refactor on the way we sort overrides when detaching instances that our tests did not caught).

I’ve marked the issue as high priority and will update you when we have any news.

**Comment by bomberstudios** [comment]
The good news is there’s a workaround you can use today, I’ll open a PR with a fix.

**Comment by Landschaft** [comment]
Another workaround is to use Sketch 90

**Comment by EricKramp** [comment]
@Landschaft, I integrated @bomberstudios patch into release `0.1.5` you should see an update soon

**Comment by Landschaft** [comment]
@EricKramp TableBuilder 0.1.5 works for me with Sketch 91 👍  (but it does not work with Sketch 90, which is no problem for me)

**Comment by bomberstudios** [comment]
> but it does not work with Sketch 90, which is no problem for me

Good catch, I should’ve added a version check before the workaround. Will do that in a minute on a new PR

**Comment by bomberstudios** [comment]
Fix added in https://github.com/EricKramp/sketch-table-builder/pull/6

**Comment by Landschaft** [comment]
[Sketch 92](https://www.sketch.com/updates/#version-92) is released and 

> Fixes a regression in the setOverrideValue method of the plugins API.

This might be the fix for the root-cause of this issue

**Comment by bomberstudios** [comment]
That’s exactly it, yes

**Comment by EricKramp** [comment]
@bomberstudios that's great, do you recommend any further updates to account for the new release?

**Comment by bomberstudios** [comment]
> @bomberstudios that's great, do you recommend any further updates to account for the new release?

Nah, you’ll be fine.
